/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BangDiem.JfrmBangDiem;
import BangDiem.JfrmTinhDiem;
import GiaoVien.JfrmGiaoVien;
import Khoa.JfrmKhoa;
import LopHoc.JfrmLopHoc;
import MonHoc.JfrmMonHoc;
import Search.JfrmSearch;
import Student.JfrmStudent;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author Tran Xuan Hao
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public static String useName;
    private Date today = new Date();
    Locale local = new Locale("vi", "VI");
    DateFormat d = DateFormat.getDateInstance(DateFormat.MEDIUM, local);
    String date = d.format(today);

    public Main() {
        initComponents();
        setUser();
        setDongHo();
    }

    public void setUser() {
        useName = JfrmLogin.useNameLogin;
        lbUser.setText(useName);
        lbHour.setText(date);

    }

    public void setDongHo() {
        Timer clock = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Calendar lich = Calendar.getInstance();
                int gio = lich.get(Calendar.HOUR);
                int phut = lich.get(Calendar.MINUTE);
                int giay = lich.get(Calendar.SECOND);
                txCurrent.setText(gio + " : " + phut + " : " + giay);
            }
        });
        clock.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel(){
            ImageIcon icon = new ImageIcon("user.png");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbHour = new javax.swing.JLabel();
        lbUser = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel(){
            ImageIcon icon = new ImageIcon("manager.jpg");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btAddStudent = new javax.swing.JButton();
        btAddTeacher = new javax.swing.JButton();
        btAddClass = new javax.swing.JButton();
        btAddSubject = new javax.swing.JButton();
        btAddKhoa = new javax.swing.JButton();
        btAddDiem = new javax.swing.JButton();
        btTinhDiem = new javax.swing.JButton();
        jtbMain = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel(){
            ImageIcon icon = new ImageIcon("Nhom.jpg");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        jLabel12 = new javax.swing.JLabel();
        txCurrent = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmSystem = new javax.swing.JMenu();
        jmiLogOff = new javax.swing.JMenuItem();
        jmiExit = new javax.swing.JMenuItem();
        jmInput = new javax.swing.JMenu();
        jmiInputStudent = new javax.swing.JMenuItem();
        jmiInputTeacher = new javax.swing.JMenuItem();
        jmiInputClass = new javax.swing.JMenuItem();
        jmiInputSubject = new javax.swing.JMenuItem();
        jmiInputMark = new javax.swing.JMenuItem();
        jmSearch = new javax.swing.JMenu();
        jmHelp = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quan Li ");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("User:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Today: ");

        lbHour.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lbHour.setForeground(new java.awt.Color(102, 0, 102));
        lbHour.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lbUser.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbHour, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbUser, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lbHour, lbUser});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                            .addComponent(lbUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbHour, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lbHour, lbUser});

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(255, 102, 204));

        jPanel5.setBackground(new java.awt.Color(0, 0, 153));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MENU");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        btAddStudent.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btAddStudent.setForeground(new java.awt.Color(0, 0, 255));
        btAddStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Item/ListMenuPatient1.png"))); // NOI18N
        btAddStudent.setText("Nhập Sinh Viên");
        btAddStudent.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddStudentActionPerformed(evt);
            }
        });

        btAddTeacher.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btAddTeacher.setForeground(new java.awt.Color(0, 0, 255));
        btAddTeacher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Item/ListMenuPatient1.png"))); // NOI18N
        btAddTeacher.setText("Nhập Giáo Viên");
        btAddTeacher.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btAddTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddTeacherActionPerformed(evt);
            }
        });

        btAddClass.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btAddClass.setForeground(new java.awt.Color(0, 0, 255));
        btAddClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Item/ListMenuPatient1.png"))); // NOI18N
        btAddClass.setText("Nhập Lớp Học   ");
        btAddClass.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btAddClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddClassActionPerformed(evt);
            }
        });

        btAddSubject.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btAddSubject.setForeground(new java.awt.Color(0, 0, 255));
        btAddSubject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Item/ListMenuPatient1.png"))); // NOI18N
        btAddSubject.setText("Nhập Môn Học");
        btAddSubject.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btAddSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddSubjectActionPerformed(evt);
            }
        });

        btAddKhoa.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btAddKhoa.setForeground(new java.awt.Color(0, 0, 255));
        btAddKhoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Item/ListMenuPatient1.png"))); // NOI18N
        btAddKhoa.setText("Nhập Khoa");
        btAddKhoa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btAddKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddKhoaActionPerformed(evt);
            }
        });

        btAddDiem.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btAddDiem.setForeground(new java.awt.Color(0, 0, 255));
        btAddDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Item/ListMenuPatient1.png"))); // NOI18N
        btAddDiem.setText("Nhập Điểm");
        btAddDiem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btAddDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddDiemActionPerformed(evt);
            }
        });

        btTinhDiem.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btTinhDiem.setForeground(new java.awt.Color(0, 0, 255));
        btTinhDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Item/ListMenuPatient1.png"))); // NOI18N
        btTinhDiem.setText("Tính Điểm");
        btTinhDiem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btTinhDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTinhDiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btAddStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAddTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAddClass)
                    .addComponent(btTinhDiem)
                    .addComponent(btAddDiem)
                    .addComponent(btAddKhoa)
                    .addComponent(btAddSubject))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btAddClass, btAddDiem, btAddKhoa, btAddStudent, btAddSubject, btAddTeacher, btTinhDiem});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAddStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btAddTeacher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btAddClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btAddSubject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(13, 13, 13)
                .addComponent(btAddKhoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btAddDiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btTinhDiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        jPanel6.setBackground(new java.awt.Color(204, 255, 204));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Student Number 1:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Student Number 3:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Student Number 2:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Student number 4:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("TRẦN XUÂN HẢO-MSSV:20121658");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("NGUYỄN VĂN ĐẢNG-MSSV:20121466");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("LÊ ĐINH KHÁNH VŨ-MSSV");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("NGUYỄN DUY LÀNH-MSSV:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Current");

        txCurrent.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txCurrent.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel11, jLabel8, jLabel9});

        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10))))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txCurrent, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel10, jLabel11, jLabel8, jLabel9});

        jtbMain.addTab("Main", jPanel6);

        jMenuBar1.setPreferredSize(new java.awt.Dimension(56, 30));

        jmSystem.setIcon(new javax.swing.ImageIcon("E:\\Bai Tap JS\\QLD\\src\\Icon\\system.png")); // NOI18N
        jmSystem.setText("System");
        jmSystem.setPreferredSize(new java.awt.Dimension(111, 24));

        jmiLogOff.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        jmiLogOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Item/Logoff.png"))); // NOI18N
        jmiLogOff.setText("Log Off");
        jmiLogOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiLogOffActionPerformed(evt);
            }
        });
        jmSystem.add(jmiLogOff);

        jmiExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jmiExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Item/logout.png"))); // NOI18N
        jmiExit.setText("Exit ");
        jmiExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiExitActionPerformed(evt);
            }
        });
        jmSystem.add(jmiExit);

        jMenuBar1.add(jmSystem);

        jmInput.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Item/1343142216_add-notes.png"))); // NOI18N
        jmInput.setText("Task");
        jmInput.setPreferredSize(new java.awt.Dimension(111, 24));

        jmiInputStudent.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        jmiInputStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Item/new.png"))); // NOI18N
        jmiInputStudent.setText("Input Student");
        jmiInputStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiInputStudentActionPerformed(evt);
            }
        });
        jmInput.add(jmiInputStudent);

        jmiInputTeacher.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK));
        jmiInputTeacher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Item/new.png"))); // NOI18N
        jmiInputTeacher.setText("Input Teacher");
        jmiInputTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiInputTeacherActionPerformed(evt);
            }
        });
        jmInput.add(jmiInputTeacher);

        jmiInputClass.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jmiInputClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Item/new.png"))); // NOI18N
        jmiInputClass.setText("Input Class");
        jmiInputClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiInputClassActionPerformed(evt);
            }
        });
        jmInput.add(jmiInputClass);

        jmiInputSubject.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        jmiInputSubject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Item/new.png"))); // NOI18N
        jmiInputSubject.setText("Input Subject");
        jmiInputSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiInputSubjectActionPerformed(evt);
            }
        });
        jmInput.add(jmiInputSubject);

        jmiInputMark.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        jmiInputMark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Item/new.png"))); // NOI18N
        jmiInputMark.setText("Input Mark");
        jmiInputMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiInputMarkActionPerformed(evt);
            }
        });
        jmInput.add(jmiInputMark);

        jMenuBar1.add(jmInput);

        jmSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Item/search2.png"))); // NOI18N
        jmSearch.setText("Search");
        jmSearch.setPreferredSize(new java.awt.Dimension(111, 24));
        jmSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmSearchMouseClicked(evt);
            }
        });
        jmSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSearchActionPerformed(evt);
            }
        });
        jMenuBar1.add(jmSearch);

        jmHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Item/Help-Support-icon.png"))); // NOI18N
        jmHelp.setText("Help");
        jmHelp.setPreferredSize(new java.awt.Dimension(111, 24));
        jMenuBar1.add(jmHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtbMain)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtbMain))
        );

        jtbMain.getAccessibleContext().setAccessibleName("Main");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAddDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddDiemActionPerformed
        // TODO add your handling code here:
        JfrmBangDiem BangDiem = new JfrmBangDiem();
        jtbMain.removeAll();
        jtbMain.add("The Mark", BangDiem);
    }//GEN-LAST:event_btAddDiemActionPerformed

    private void btAddTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddTeacherActionPerformed
        // TODO add your handling code here:
        JfrmGiaoVien gv = new JfrmGiaoVien();
        jtbMain.removeAll();
        jtbMain.add("Teacher Information", gv);
    }//GEN-LAST:event_btAddTeacherActionPerformed

    private void btAddClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddClassActionPerformed
        // TODO add your handling code here:
        JfrmLopHoc Class = new JfrmLopHoc();
        jtbMain.removeAll();
        jtbMain.add("Class Information", Class);
    }//GEN-LAST:event_btAddClassActionPerformed

    private void jmSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSearchActionPerformed
        // TODO add your handling code here:
        JfrmSearch timkiem = new JfrmSearch();
        jtbMain.removeAll();
        jtbMain.add("Search", timkiem);
    }//GEN-LAST:event_jmSearchActionPerformed

    private void jmSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmSearchMouseClicked
        // TODO add your handling code here:
        JfrmSearch tkiem = new JfrmSearch();
        jtbMain.removeAll();
        jtbMain.add("Search", tkiem);
    }//GEN-LAST:event_jmSearchMouseClicked

    private void btAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddStudentActionPerformed
        // TODO add your handling code here:
        JfrmStudent student = new JfrmStudent();
        jtbMain.removeAll();
        jtbMain.add("Student Information", student);
    }//GEN-LAST:event_btAddStudentActionPerformed

    private void btAddSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddSubjectActionPerformed
        // TODO add your handling code here:
        JfrmMonHoc monHoc = new JfrmMonHoc();
        jtbMain.removeAll();
        jtbMain.add("Subject Information", monHoc);
    }//GEN-LAST:event_btAddSubjectActionPerformed

    private void btAddKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddKhoaActionPerformed
        // TODO add your handling code here:
        JfrmKhoa khoa = new JfrmKhoa();
        jtbMain.removeAll();
        jtbMain.add("Faculty Information", khoa);
    }//GEN-LAST:event_btAddKhoaActionPerformed

    private void btTinhDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTinhDiemActionPerformed
        // TODO add your handling code here:
        JfrmTinhDiem Mark = new JfrmTinhDiem();
        jtbMain.removeAll();
        jtbMain.add("Mark", Mark);
    }//GEN-LAST:event_btTinhDiemActionPerformed

    private void jmiLogOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiLogOffActionPerformed
        // TODO add your handling code here:
        dispose();
        JfrmLogin login = new JfrmLogin();
        login.setVisible(true);
    }//GEN-LAST:event_jmiLogOffActionPerformed

    private void jmiExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jmiExitActionPerformed

    private void jmiInputStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiInputStudentActionPerformed
        // TODO add your handling code here:
        JfrmStudent student = new JfrmStudent();
        jtbMain.removeAll();
        jtbMain.add("Student Information", student);
    }//GEN-LAST:event_jmiInputStudentActionPerformed

    private void jmiInputTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiInputTeacherActionPerformed
        // TODO add your handling code here:
        JfrmGiaoVien gv = new JfrmGiaoVien();
        jtbMain.removeAll();
        jtbMain.add("Teacher Information", gv);
    }//GEN-LAST:event_jmiInputTeacherActionPerformed

    private void jmiInputClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiInputClassActionPerformed
        // TODO add your handling code here:
        JfrmLopHoc Class = new JfrmLopHoc();
        jtbMain.removeAll();
        jtbMain.add("Class Information", Class);
    }//GEN-LAST:event_jmiInputClassActionPerformed

    private void jmiInputSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiInputSubjectActionPerformed
        // TODO add your handling code here:
        JfrmMonHoc monHoc = new JfrmMonHoc();
        jtbMain.removeAll();
        jtbMain.add("Subject Information", monHoc);
    }//GEN-LAST:event_jmiInputSubjectActionPerformed

    private void jmiInputMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiInputMarkActionPerformed
        // TODO add your handling code here:
        JfrmBangDiem BangDiem = new JfrmBangDiem();
        jtbMain.removeAll();
        jtbMain.add("The Mark", BangDiem);
    }//GEN-LAST:event_jmiInputMarkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddClass;
    private javax.swing.JButton btAddDiem;
    private javax.swing.JButton btAddKhoa;
    private javax.swing.JButton btAddStudent;
    private javax.swing.JButton btAddSubject;
    private javax.swing.JButton btAddTeacher;
    private javax.swing.JButton btTinhDiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JMenu jmHelp;
    private javax.swing.JMenu jmInput;
    private javax.swing.JMenu jmSearch;
    private javax.swing.JMenu jmSystem;
    private javax.swing.JMenuItem jmiExit;
    private javax.swing.JMenuItem jmiInputClass;
    private javax.swing.JMenuItem jmiInputMark;
    private javax.swing.JMenuItem jmiInputStudent;
    private javax.swing.JMenuItem jmiInputSubject;
    private javax.swing.JMenuItem jmiInputTeacher;
    private javax.swing.JMenuItem jmiLogOff;
    private javax.swing.JTabbedPane jtbMain;
    private javax.swing.JLabel lbHour;
    private javax.swing.JLabel lbUser;
    private javax.swing.JTextField txCurrent;
    // End of variables declaration//GEN-END:variables
}
